### ISSUE TITLE
Uniendome al reto con Steven Universe

### ISSUE THREAD

**Issue by alexcamachogz** [musartedev/dibujarte-css#1]
Nombre: Alejandra Camacho
Portafolio: [Steven Universe](https://codepen.io/alexcamachogz/pen/PoNYRWK)
Red social: [@alexcamachogz](https://twitter.com/alexcamachogz)

**Comment by musartedev** [comment]
Listo, @alexcamachogz ! Te quedó genial. Ya está agregado.

Gracias!
