### ISSUE TITLE
🎨  [Art] - Pure CSS Nintendo GameBoy

### ISSUE THREAD

**Issue by baumannzone** [musartedev/dibujarte-css#14]
## 🎨  Nuevo arte: - Pure CSS Nintendo GameBoy
🔸  **Codepen:** https://codepen.io/baumann/pen/YQKbqW

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre:** Jorge Baumann
🔸  **Twitter:** https://twitter.com/baumannzone
🔸  **Github:** https://github.com/baumannzone/gameboy-css

![image](https://user-images.githubusercontent.com/5422102/91490942-89fbec00-e8b3-11ea-991f-8390aa629a7c.png)

**Comment by musartedev** [comment]
Agregado, me encantó tu trabajo
