### ISSUE TITLE
🎨  [Art] - 

### ISSUE THREAD

**Issue by MemoBrown** [musartedev/dibujarte-css#15]
## 🎨  Nuevo arte: - <Rick Sanchez>
🔸  **Codepen:** https://codepen.io/MemoBrown/pen/zYvmxGX

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre:** Guillermo Moreno
🔸  **Twitter:** [@MemoBrown_](https://twitter.com/MemoBrown_)
🔸  **Github:** [MemoBrown](https://github.com/MemoBrown
![Captura de pantalla de 2020-08-28 10-29-16](https://user-images.githubusercontent.com/53451288/91585216-6075ab80-e919-11ea-879c-c02fd63dd084.png)
)

**Comment by musartedev** [comment]
Agregado, Memo. Gracias <3
