### ISSUE TITLE
🎨  [Art] - Pikachu #DibujarteCSS

### ISSUE THREAD

**Issue by CristhianM01** [musartedev/dibujarte-css#16]
## 🎨  Nuevo arte: - Pikachu #DibujarteCSS
🔸  **Codepen:** https://codepen.io/cristhianm01/pen/MWyojmz

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre:** Cristhian Mahecha
🔸  **Github:** https://github.com/CristhianM01/Pikachu-CSS3.git

![pika](https://user-images.githubusercontent.com/66317820/91619718-81f38900-e953-11ea-8d5f-3a9c87501ce4.PNG)

**Comment by musartedev** [comment]
Wowowow, me encantó este Pikachú 🤩. Ya lo agregué, felicidades, buen trabajo!
