### ISSUE TITLE
🎨  [Art] - Pokemon Gengar

### ISSUE THREAD

**Issue by ruben-salgado** [musartedev/dibujarte-css#17]
## 🎨  Nuevo arte: - <Nombre del arte>
🔸  **Codepen: https://codepen.io/rubensal/pen/rNeLYLV?editors=1100**

### 👩🏽‍🎨 Autor
🔸  **Nombre: Rubén Salgado** 
🔸  **Twitter: @RubenSal_dev**
🔸  **Github: https://github.com/ruben-salgado/artcss-pokemon-gengar.git**

**Comment by musartedev** [comment]
Brutal!

**Comment by musartedev** [comment]
Agregado <3
