### ISSUE TITLE
🎨  [Art] - Bb-8 De Star Wars

### ISSUE THREAD

**Issue by Kelvin-Joel** [musartedev/dibujarte-css#21]
## 🎨  Nuevo arte: - <Bb-8 Star Wars>
🔸  **Codepen:** https://codepen.io/joelkelvin-vh/pen/ExKbmgJ

### 👩🏽‍🎨 Autor(a)Kelvin Ventura
🔸  **Nombre:** Kelvin Joel
🔸  **Twitter:** https://twitter.com/joel_kelvin19?s=09
🔸  **Github:** https://github.com/JKPROGR/Bb8.git

**Comment by musartedev** [comment]
Excelente, Kelvin!!
Mañana lo estaré agregando.

**Comment by musartedev** [comment]
Super buen trabajo, Kelvin. Lo detallé más hoy, brutal. Ya lo agregué. Gracias por tu aporte.
