### ISSUE TITLE
🎨  [Art] - Analog Clock

### ISSUE THREAD

**Issue by AndresParraGO** [musartedev/dibujarte-css#23]
## 🎨  Nuevo arte: - Analog Clock
🔸  https://codepen.io/andresparragarzon/pen/LYRgoeK

### 👩🏽‍🎨 Autor(a)
🔸  Andrés Parra Garzón
🔸  https://twitter.com/AndresParraGar4
🔸  https://github.com/AndresParraGO

**Comment by musartedev** [comment]
Andrés <3. Excelente trabajo como siempre 🤩 . Ya quedó agregado
