### ISSUE TITLE
🎨  [Art] - Jirafita en CSS 

### ISSUE THREAD

**Issue by Photographya** [musartedev/dibujarte-css#24]
## 🎨  Nuevo arte: - Jirafita

🔸 https://codepen.io/Photographya/pen/wvopMzK

### 👩🏽‍🎨 Autor(a)
🔸  Nombre: Israel Vásquez Baltazar
🔸  Twitter: @IrrealeRiquadri
🔸  Github: https://github.com/Photographya

**Comment by musartedev** [comment]
Qué bonito. Me gustó mucho el resultado. Más tardecito lo agrego <3

**Comment by musartedev** [comment]
Ya quedó agregado, Israel 🤩
