### ISSUE TITLE
🎨  [Art] - 

### ISSUE THREAD

**Issue by juliolh0686** [musartedev/dibujarte-css#25]
## 🎨  Nuevo arte: Televisor
🔸  https://codepen.io/juliolh06/pen/BaQJJGz?editors=1100

### 👩🏽‍🎨 Autor(a)
🔸  Julio Loarte Huerto
🔸  @Juliolh06
🔸  https://github.com/juliolh0686

**Comment by musartedev** [comment]
Wow. Qué espectacular. ¿Es diseño propio? O te guiaste de una imagen (solo curiosidad). Más tardecito lo agrego <3

**Comment by musartedev** [comment]
Agregado, Julio <3

**Comment by juliolh0686** [comment]
Gracias (y) , Si me guie de una imagen de internet. :)
