### ISSUE TITLE
🎨  [Art] - Mishi con CSS

### ISSUE THREAD

**Issue by daniel692a** [musartedev/dibujarte-css#26]
## 🎨  Nuevo arte: Mishi
🔸  https://codepen.io/daniel692/pen/mdOLrbp

### 👩🏽‍🎨 Autor(a)
🔸  Nombre: Daniel Armas Ramírez 
🔸  Twitter: https://twitter.com/daniel_ar_962
🔸  Github: https://github.com/daniel692a

**Comment by musartedev** [comment]
Buen trabajo, Daniel 🤩  ¿Cómo te sentiste haciéndolo? 
Te comento que ya fue agregado tu arte <3
