### ISSUE TITLE
🎨  [Art] - 

### ISSUE THREAD

**Issue by Medotq** [musartedev/dibujarte-css#27]
## 🎨  Nuevo arte: - The Space
🔸  **Codepen:** https://codepen.io/sebdidesign/pen/ZEBjpNG

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre:** Sebastián Díaz
🔸  **Twitter:** @sebdidesign
🔸  **Github:** https://github.com/Medotq
![Screenshot_1](https://user-images.githubusercontent.com/79531149/109996298-152fc180-7cdd-11eb-9b3c-8e724091a4fa.png)

**Comment by Medotq** [comment]
Mi primer draw en css

**Comment by musartedev** [comment]
Excelente! Te quedó super genial 🤩 . Ya quedó agregado! ¿Cómo te sentiste haciéndolo?
