### ISSUE TITLE
🎨  [Art] - 

### ISSUE THREAD

**Issue by JesusCH92** [musartedev/dibujarte-css#28]
## 🎨  Nuevo arte: - Baby Yoda
🔸  **Codepen:** https://github.com/JesusCH92/maquetacion--baby-yoda

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre:** Jesús
🔸  **Twitter:** https://twitter.com/DddTarea
🔸  **Github:** https://github.com/JesusCH92

**Comment by musartedev** [comment]
Excelente trabajo 🤩 . Ya quedó agregado. ¿Cómo te sentiste haciéndolo?

**Comment by JesusCH92** [comment]
Muchas gracias, ha sido muy satisfactorio poder terminarlos, me ha encantado la idea de dibujarte-css
________________________________
De: Mariangélica Useche <notifications@github.com>
Enviado: martes, 9 de marzo de 2021 15:53
Para: musartedev/dibujarte-css <dibujarte-css@noreply.github.com>
Cc: JesusCH92 <jcocaharo@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [musartedev/dibujarte-css] 🎨 [Art] - (#28)


Excelente trabajo 🤩 . Ya quedó agregado. ¿Cómo te sentiste haciéndolo?
