### ISSUE TITLE
🍩  Homero Simpson

### ISSUE THREAD

**Issue by JoEduardoReyes** [musartedev/dibujarte-css#30]
## 🎨  Nuevo arte: - Homero Simpson
🔸  **Codepen:** [codepen.io/JoEduardoReyes/pen/LYbJBVr](https://codepen.io/JoEduardoReyes/pen/LYbJBVr)

### 👩🏽‍🎨 Autor
🔸  **Nombre:** Eduardo Reyes
🔸  **Twitter:** [twitter.com/JoEduardoReyes](https://twitter.com/JoEduardoReyes)
🔸  **Github:** [github.com/JoEduardoReyes](https://github.com/JoEduardoReyes)

**Comment by musartedev** [comment]
Te quedó super, Eduardo. Ya lo agregué ⭐
