### ISSUE TITLE
🎨  [Art] - Chess Board

### ISSUE THREAD

**Issue by DavidOsorioLeyva** [musartedev/dibujarte-css#32]
## 🎨  Nuevo arte: - Chess Board
🔸  **Codepen: https://github.com/DavidOsorioLeyva/chessboard**

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre: David Osorio Leyva** 
🔸  **Twitter: https://twitter.com/soyDavidOsorio**
🔸  **Github: https://github.com/DavidOsorioLeyva**

**Comment by musartedev** [comment]
Ya fue agregado tu arte, David. Gran trabajo!
