### ISSUE TITLE
🎨  [Art] - 

### ISSUE THREAD

**Issue by Manuel-2** [musartedev/dibujarte-css#34]
## 🎨  Nuevo arte: - Un Pequeño Charmander
🔸  **Codepen:** https://codepen.io/manuel-2/pen/eYgdeQr

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre:** Manuel Peñaloza
🔸  **Twitter:**  @Manuel09779534
🔸  **Github:**  https://github.com/Manuel-2

**Comment by musartedev** [comment]
Wowow. Me encanta el estilo minimalista. Lo estaré agregando pronto a la galería <3

**Comment by musartedev** [comment]
Ya quedó <3
