### ISSUE TITLE
🎨 Kakashi CSS 🐱‍💻

### ISSUE THREAD

**Issue by Alincut** [musartedev/dibujarte-css#35]
## 🎨  Nuevo arte: Kakashi CSS
🔸  **Codepen:** https://alincut.github.io/kakashi/

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre:** Leonardo Alain
🔸  **Twitter:** https://twitter.com/Allin826381
🔸  **Github:** https://github.com/Alincut

**Comment by musartedev** [comment]
Quedó agregado. Felicidades. ¿Cómo te sentiste en el proceso?

**Comment by Alincut** [comment]
Fue divertido y un poco agotador, pensé que sería más rápido jeje. Sin embargo el proceso fue entusiasmante y el resultado aún más!! 😎😁
