### ISSUE TITLE
🎨  [Art] - 

### ISSUE THREAD

**Issue by AlexanderLGRS** [musartedev/dibujarte-css#36]
## 🎨  Nuevo arte: - <Stitch>
🔸  **Codepen: https://codepen.io/alexanderlgrs/pen/dyNmXWK**

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre: Alexander Lansdorp Girón** 
🔸  **Twitter: @GironLansdorp**
🔸  **Github: https://github.com/AlexanderLGRS**

**Comment by musartedev** [comment]
Agregado a la galería ⭐ Gracias por sumarte, Alexander. ¿Qué tal te sentiste?
