### ISSUE TITLE
🎨  [Art] - La parca

### ISSUE THREAD

**Issue by mabmab159** [musartedev/dibujarte-css#37]
## 🎨  Nuevo arte: - La parca
🔸  Codepen: https://codepen.io/mabmab159/pen/LYxqLqq

### 👩🏽‍🎨 Autor(a)
🔸  Nombre: Miguel Angel Berrio Huamani
🔸  Twitter: https://twitter.com/mabmab0159
🔸  Github: https://github.com/mabmab159

**Comment by musartedev** [comment]
Excelente trabajo, Miguel! Ya fue agregado a la galería
