### ISSUE TITLE
🎨  [Art] - Deathly hallows

### ISSUE THREAD

**Issue by Sergio9815** [musartedev/dibujarte-css#38]
## 🎨  Nuevo arte: - Deathly hallows
🔸  **Link: https://dh-cartoon-css.vercel.app/**

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre: Sergio González** 
🔸  **Instagram: https://www.instagram.com/sagb_24/**
🔸  **Github: https://github.com/Sergio9815**

**Comment by musartedev** [comment]
Genial, buen trabajo, Sergio. Ya fue agregado a la galería
