### ISSUE TITLE
🎨  [Art] - Zombie with CSS

### ISSUE THREAD

**Issue by carloscdev** [musartedev/dibujarte-css#39]
## 🎨  Nuevo arte: - <Nombre del arte>
🔸  **Codepen: https://codepen.io/carloscdev/pen/rNyJJYY**

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre: Carlos Córdova** 
🔸  **Twitter: @carloscdev**
🔸  **Github: @carloscdev**

**Comment by musartedev** [comment]
Brutal, me comió el cerebro este dibujo!! jaja. Ya fue agregado a la galería
