### ISSUE TITLE
🎨  [Art] - Doraemon with css

### ISSUE THREAD

**Issue by denver15-jh** [musartedev/dibujarte-css#40]
## 🎨  Nuevo arte: - <Nombre del arte>
🔸  **Codepen:** https://codepen.io/denver15jh/pen/GRWxMjP

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre:** José Hernández
🔸  **Twitter:** https://twitter.com/denver15jh
🔸  **Github:** https://github.com/denver15-jh

**Comment by musartedev** [comment]
Excelente. Me trae recuerdos esa ilustración. Felicidades. Ya fue agregado a la galería
