### ISSUE TITLE
🎨  GARU

### ISSUE THREAD

**Issue by Brandon328** [musartedev/dibujarte-css#41]
## 🎨  Nuevo arte: Dibujo de GARU con CSS
🔸  Codepen: https://codepen.io/brandon328/pen/mdWLoGJ

### 👩🏽‍🎨 Autor(a)
🔸  Nombra: Brandon James Huamán Mallcco
🔸  Github: https://github.com/Brandon328

**Comment by musartedev** [comment]
¡Genial, Brandon! Ya fue agregada tu ilustración 👏🏽
