### ISSUE TITLE
🎨  [Art] - Pollito volador

### ISSUE THREAD

**Issue by mfranchi82** [musartedev/dibujarte-css#42]
## 🎨  Nuevo arte: - Pollito volador
🔸  https://codepen.io/mfranchi82/pen/VwpEpLE?editors=1100

### 👩🏽‍🎨 Autor(a)
🔸 Miguel Franchi
🔸 https://twitter.com/mfranchi82
🔸  https://github.com/mfranchi82/

**Comment by musartedev** [comment]
Brutal!! Me gustó el Pollito Volador 🐣 . Ya fue agregado a la galería 👍🏽
