### ISSUE TITLE
🎨  [Art] - Cuphead 

### ISSUE THREAD

**Issue by Mike-droid** [musartedev/dibujarte-css#43]
## 🎨  Nuevo arte: - <Cuphead>
🔸  
https://codepen.io/mike-droid/pen/WNpmLJL

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre: Miguel Ángel Reyes Moreno** 
🔸  **Twitter: @MiguelAngelRe28**
🔸  **Github: https://github.com/Mike-droid**

**Comment by musartedev** [comment]
Hola, Mike!! Qué genial que te hayas sumado al reto <3. ¿Podrías subir tu arte a http://codepen.io/?

**Comment by musartedev** [comment]
Hola, Mike. Ya quedó agregado tu arte 🤩
