### ISSUE TITLE
🎨  [Art] - #DibujarteCSS @musartedev

### ISSUE THREAD

**Issue by doncanzsa** [musartedev/dibujarte-css#45]
## 🎨  Nuevo arte: Calvito
🔸  **Codepen:** https://codepen.io/doncanzsa/pen/xxrRrBB

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre:** Stanley Alvarez
🔸  **Twitter:**
🔸  **Github:** https://github.com/doncanzsa

**Comment by musartedev** [comment]
Hola, @doncanzsa  <3 Ya tu arte quedó agregado a la galería 🌟
