### ISSUE TITLE
🎨  [Art] - Axie Infinity

### ISSUE THREAD

**Issue by ca7seven** [musartedev/dibujarte-css#47]
## 🎨  Nuevo arte: - Axie Infinity
🔸  **Codepen: https://codepen.io/ca7seven/pen/abyXKex**

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre: Gastón Ezequiel Papa** 
🔸  **Twitter: https://twitter.com/cAtSeVeN_G7**
🔸  **Github: https://github.com/ca7seven**

**Comment by musartedev** [comment]
Ya quedó agregado tu arte ⭐  Quedó genial <3
