### ISSUE TITLE
🎨  [Art] - Earth - flat design

### ISSUE THREAD

**Issue by ricandres98** [musartedev/dibujarte-css#48]
## 🎨  Nuevo arte: - Tierra-css
🔸  **Codepen:** https://codepen.io/ricandres98/pen/YzrJZYV

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre:** Ricardo Ojeda
🔸  **Twitter:** @ricandres_98
🔸  **Github:** https://github.com/ricandres98/Dibujos-con-CSS

**Comment by musartedev** [comment]
¡Me encantó! Ya fue agregado a la galería <3
