### ISSUE TITLE
🎨  [Art] - Unicorn Llama

### ISSUE THREAD

**Issue by rodruxdev** [musartedev/dibujarte-css#49]
## 🎨  Nuevo arte: - <Nombre del arte>
🔸  **Codepen:** [Unicorn Llama Codepen](https://codepen.io/rodruxdev/pen/xxXBeOY)

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre:** Rodrigo Goitia
🔸  **Twitter:** [@rodruxdev](https://twitter.com/rodruxdev)
🔸  **Github:** [rodruxdev](https://github.com/rodruxdev)

**Comment by musartedev** [comment]
Te lo dije por twitter: qué bonito. Quedó agregado a la galería <3

**Comment by rodruxdev** [comment]
Muchisimas gracias! Sobre todo por la motivación para dibujar <3
