### ISSUE TITLE
🎨  [Art] - Fat Heisenberg by CricaDev

### ISSUE THREAD

**Issue by CristianN998** [musartedev/dibujarte-css#50]
## 🎨  Nuevo arte: - <Fat Heisenberg>
🔸  **Codepen: https://codepen.io/cristiann998/pen/bGYBONY
🔸  **Github pages: https://cristiann998.github.io/Desktop/curso-pro-css-grid/dibujarte-css/index.html

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre: Cristian Casallas
🔸  **Twitter: https://twitter.com/CristianN998
🔸  **Github: https://github.com/CristianN998

**Comment by musartedev** [comment]
Excelente trabajo. Vi que cambiaste el usuario de twitter, así que puse el nuevo <3 . Agregado a la galería
