### ISSUE TITLE
🎨  [Art] - Ojo Animado

### ISSUE THREAD

**Issue by Kelvin-Joel** [musartedev/dibujarte-css#52]
## 🎨  Nuevo arte: 👁 Ojo Animado
🔸  **Codepen: https://codepen.io/joelkelvin-vh/pen/XWZEeyb **

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre: Joel Ventura** 
🔸  **Twitter:https://twitter.com/joel_kelvin19 **
🔸  **Github: https://github.com/Kelvin-Joel **

**Comment by musartedev** [comment]
Joel, me encanta tu dedicación y cómo mejoras tu dibujos <3 Ya está en la galería. Increíble, como siempre
