### ISSUE TITLE
🎨  [Art] -  Luffy - OnePiece

### ISSUE THREAD

**Issue by jonathanviro** [musartedev/dibujarte-css#53]
## 🎨  Nuevo arte: - <Luffy>
🔸  **Codepen: https://codepen.io/jonathanviro/pen/oNqoZYE**

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre: Jonathan Vivero Rodriguez** 
🔸  **Twitter: https://twitter.com/jonvirodev**
🔸  **Github: https://github.com/jonathanviro**
![luffy-jonviroev](https://user-images.githubusercontent.com/105942530/181834206-4d3f560a-06a6-483f-a550-6f7a018e2308.png)

**Comment by musartedev** [comment]
Ya en la galería <3 https://dibujartecss.musarte.dev/
