### ISSUE TITLE
🎨  [Art] - Mi primer dibujo con CSS

### ISSUE THREAD

**Issue by erikabernalm** [musartedev/dibujarte-css#54]
## 🎨  Nuevo arte: Mi primer dibujo con CSS
🔸  **Codepen:** https://codepen.io/erikabernalm/pen/VwXrOpO

### 👩🏽‍🎨 Autor(a)
🔸  **Nombre:** Erika Nathaly Bernal Morales
🔸  **Twitter:**
🔸  **Github:** https://github.com/erikabernalm/dibujemos-con-CSS

**Comment by erikabernalm** [comment]
Hola, mi nombre es Erika. Soy orgullosamente Platzinauta y estoy tomando el curso Profesional de CSS Grid Layout. Hoy hice mi primer dibujo con CSS como parte de un reto de este curso. 

Quiero que mi dibujo esté en la galería. Gracias!!! 😀💚

**Comment by musartedev** [comment]
¡Felicidaes, Erika! ¿Cómo te sentiste en el proceso? 

Ya tu arte está en la galería: https://dibujartecss.musarte.dev/

**Comment by erikabernalm** [comment]
Hola @musartedev muchas gracias!!!

Me sentí muy bien durante el proceso de creación porque aunque tomó varias horas pude aplicar lo aprendido en el curso de CSS  Grid. Fue todo un reto pero se logró! 💪💻💚👩‍🎨
Espero más adelante hacer más dibujos. La galería está genial!!

Ahí actualicé mis datos, también tengo twitter 👉 https://twitter.com/erikabernalm
